---
- include: site.yml

- hosts: [rvm]
  roles:
    - role: rvm_io.ruby
      become: yes
      when: rvm1_rubies|length > 0

- hosts: [nginx]
  roles:
    - role: geerlingguy.nginx
      become: yes

- hosts: [passenger]
  roles:
    - role: geerlingguy.passenger
      become: yes
