---
- include: site.yml

- hosts: [nginx]
  roles:
    - role: geerlingguy.nginx
      become: yes

- hosts: [mysql]
  roles:
    - role: geerlingguy.mysql
      become: yes

- hosts: [php]
  roles:
    - role: geerlingguy.php
      become: yes
    - role: geerlingguy.composer
      become: yes
