---
java_product: jre
java_version: 8
java_shell_profile: true

eclipse_distro: mars 
eclipse_package: php
eclipse_plugins:
  - egit
  - symfony
  - makegood 
  - redmine_mylyn

package_list_eclipse: []

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "symfony.local"
    root: "/project/web"
    error_log:   /var/log/nginx/symfony_error.log
    access_log:  /var/log/nginx/symfony_access.log
    extra_parameters: |
      rewrite     ^/(app|app_dev)\.php/?(.*)$ /$1 permanent;
      
      location / {
        index       app_dev.php;
        try_files   $uri @rewriteapp;
      }
      
      location @rewriteapp {
        rewrite     ^(.*)$ /app_dev.php/$1 last;
      }
      
      location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass            unix:/var/run/symfony.sock;
        fastcgi_buffer_size     16k;
        fastcgi_buffers         4 16k;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include                 fastcgi_params;
        fastcgi_param           SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param           HTTPS           off;
      }

mysql_databases:
  - name:  symfony
    state: present

mysql_users:
  - name:           "symfony"
    password:       "symfony"
    priv:           "symfony.*:ALL"
    host:           "localhost"
    state:          present
